In [4]:
import pandas as pd

In [5]:
df = pd.read_csv(
    "/content/IMDB Dataset.csv",
    encoding = 'latin1',
    engine = 'python',
    on_bad_lines='skip'
)

df

                                                  review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
11033  Zentropa has much in common with The Third Man...  positive
11034  WARNING:I advise anyone who has not seen the f...  negative
11035  Ego. Seems it's the only reason this movie was...  negative
11036  This is meant to be a comedy but mainly bad ta...  negative
11037  Typically, "kids" films have some annoying qua...  positive

[11038 rows x 2 columns]

In [6]:
df.columns

Index(['review', 'sentiment'], dtype='object')

In [7]:
df['review'] = df['review'].str.lower()

In [8]:
df['review']

0        one of the other reviewers has mentioned that ...
1        a wonderful little production. <br /><br />the...
2        i thought this was a wonderful way to spend ti...
3        basically there's a family where a little boy ...
4        petter mattei's "love in the time of money" is...
                               ...
11033    zentropa has much in common with the third man...
11034    warning:i advise anyone who has not seen the f...
11035    ego. seems it's the only reason this movie was...
11036    this is meant to be a comedy but mainly bad ta...
11037    typically, "kids" films have some annoying qua...
Name: review, Length: 11038, dtype: object

In [9]:
df['review'][3]

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.<br /><br />ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

# Remove HTML Tags

In [10]:
import re

def remove_html_tags(text):
  pattern = re.compile(r"<.*?>")
  return pattern.sub(r'', text)

In [11]:
remove_html_tags(df['review'][3])

"basically there's a family where a little boy (jake) thinks there's a zombie in his closet & his parents are fighting all the time.this movie is slower than a soap opera... and suddenly, jake decides to become rambo and kill the zombie.ok, first of all when you're going to make a film you must decide if its a thriller or a drama! as a drama the movie is watchable. parents are divorcing & arguing like in real life. and then we have jake with his closet which totally ruins all the film! i expected to see a boogeyman similar movie, and instead i watched a drama with some meaningless thriller spots.3 out of 10 just for the well playing parents & descent dialogs. as for the shots with jake: just ignore them."

# Remove URL

In [12]:
def remove_url(text):
  pattern = re.compile(r"https?://\S+|www\.\S+")
  return pattern.sub(r"", text)

In [13]:
# for testing the remove url fun
text1= '''
Yesterday, I was exploring resources to learn Machine Learning and NLP. I found some excellent materials on https://phitron.io and also watched tutorials at https://www.youtube.com/watch?v=dQw4w9WgXcQ.

For research papers, I visited https://arxiv.org/abs/1706.03762 and read documentation from https://pytorch.org/docs/stable/index.html. One of my friends also shared a blog post available at www.medium.com/@ai_engineer/transformers-explained.

If you'd like to practice coding problems, check out https://leetcode.com/problemset/ or https://www.kaggle.com/datasets. These websites are very helpful for aspiring AI engineers.

'''

In [14]:
text1 = remove_url(text1)

In [15]:
text1

"\nYesterday, I was exploring resources to learn Machine Learning and NLP. I found some excellent materials on  and also watched tutorials at \n\nFor research papers, I visited  and read documentation from  One of my friends also shared a blog post available at \n\nIf you'd like to practice coding problems, check out  or  These websites are very helpful for aspiring AI engineers.\n\n"

# Remove Punctuation

In [16]:
import string

way 1

In [17]:
exclude = string.punctuation
exclude

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [18]:
def remove_punc(text):
  for char in exclude:
    text = text.replace(char,"")

  return text

In [19]:
remove_punc("ratul,!!!? say hi to everyone.")

'ratul say hi to everyone'

way 2

In [20]:
def remove_punc1(text):
  return text.translate(str.maketrans(' ', ' ', exclude))

In [21]:
remove_punc1("Hello, everyone how do you feel???!!! I know whats going there. But I act like idk.")

'Hello everyone how do you feel I know whats going there But I act like idk'

# Chat words treatment

In [22]:
chat_words = {
    "A3": "Anytime, Anywhere, Anyplace",
    "ADIH": "Another Day In Hell",
    "AFK": "Away From Keyboard",
    "AFAIK": "As Far As I Know",
    "ASAP": "As Soon As Possible",
    "ATK": "At The Keyboard",
    "ATM": "At The Moment",
    "BAE": "Before Anyone Else",
    "BAK": "Back At Keyboard",
    "BBL": "Be Back Later",
    "BBS": "Be Back Soon",
    "BFN": "Bye For Now",
    "B4N": "Bye For Now",
    "BRB": "Be Right Back",
    "BRUH": "Bro",
    "BRT": "Be Right There",
    "BSAAW": "Big Smile And A Wink",
    "BTW": "By The Way",
    "BWL": "Bursting With Laughter",
    "CSL": "Can’t Stop Laughing",
    "CU": "See You",
    "CUL8R": "See You Later",
    "CYA": "See You",
    "DM": "Direct Message",
    "FAQ": "Frequently Asked Questions",
    "FC": "Fingers Crossed",
    "FIMH": "Forever In My Heart",
    "FOMO": "Fear Of Missing Out",
    "FR": "For Real",
    "FWIW": "For What It's Worth",
    "FYP": "For You Page",
    "FYI": "For Your Information",
    "G9": "Genius",
    "GAL": "Get A Life",
    "GG": "Good Game",
    "GMTA": "Great Minds Think Alike",
    "GN": "Good Night",
    "GOAT": "Greatest Of All Time",
    "GR8": "Great!",
    "HBD": "Happy Birthday",
    "IC": "I See",
    "ICQ": "I Seek You",
    "IDC": "I Don’t Care",
    "IDK": "I Don't Know",
    "IFYP": "I Feel Your Pain",
    "ILU": "I Love You",
    "ILY": "I Love You",
    "IMHO": "In My Honest/Humble Opinion",
    "IMU": "I Miss You",
    "IMO": "In My Opinion",
    "IOW": "In Other Words",
    "IRL": "In Real Life",
    "IYKYK": "If You Know, You Know",
    "JK": "Just Kidding",
    "KISS": "Keep It Simple, Stupid",
    "L": "Loss",
    "L8R": "Later",
    "LDR": "Long Distance Relationship",
    "LMK": "Let Me Know",
    "LMAO": "Laughing My A** Off",
    "LOL": "Laughing Out Loud",
    "LTNS": "Long Time No See",
    "M8": "Mate",
    "MFW": "My Face When",
    "MID": "Mediocre",
    "MRW": "My Reaction When",
    "MTE": "My Thoughts Exactly",
    "NVM": "Never Mind",
    "NRN": "No Reply Necessary",
    "NPC": "Non-Player Character",
    "OIC": "Oh I See",
    "OP": "Overpowered",
    "POV": "Point Of View",
    "PRT": "Party",
    "PRW": "Parents Are Watching",
    "ROFL": "Rolling On The Floor Laughing",
    "ROFLOL": "Rolling On The Floor Laughing Out Loud",
    "ROTFLMAO": "Rolling On The Floor Laughing My A** Off",
    "RN": "Right Now",
    "SK8": "Skate",
    "SUS": "Suspicious",
    "TBH": "To Be Honest",
    "TFW": "That Feeling When",
    "THX": "Thank You",
    "TIME": "Tears In My Eyes",
    "TLDR": "Too Long, Didn’t Read",
    "TNTL": "Trying Not To Laugh",
    "TTFN": "Ta-Ta For Now!",
    "TTYL": "Talk To You Later",
    "U": "You",
    "U2": "You Too",
    "U4E": "Yours For Ever",
    "W": "Win",
    "W8": "Wait...",
    "WB": "Welcome Back",
    "WTG": "Way To Go!",
    "WUF": "Where Are You From?",
    "WYD": "What You Doing?",
    "WYWH": "Wish You Were Here",
    "ZZZ": "Sleeping, Bored, Tired",
    "OMG!": "Oh My God",
    "SMH": "Shaking My Head",
    "NGL": "Not Gonna Lie",
    "TBF": "To Be Fair",
    "ICYMI": "In Case You Missed It",
    "IMO": "In My Opinion",
    "IMHO": "In My Honest Opinion",
    "RN": "Right Now",
    "FR": "For Real",
    "DW": "Don't Worry",
    "ILYSM": "I Love You So Much",
    "OMW": "On My Way",
    "GGWP": "Good Game Well Played",
    "GG": "Good Game",
    "EZ": "Easy",
    "LMAO": "Laughing My A** Off",
    "LOL": "Laughing Out Loud"
}

In [23]:
def chat_conversion(text):
  new_text = []

  for w in text.split():
    if w.upper() in chat_words:
      new_text.append(chat_words[w.upper()])
    else:
      new_text.append(w)

  return " ".join(new_text)

In [24]:
chat_conversion("AFK omg!")

'Away From Keyboard Oh My God'

# Spell checking

In [25]:
from textblob import TextBlob

In [26]:
incorrect_text = "hellllo this is jack"

In [27]:
textblb = TextBlob(incorrect_text)

In [28]:
textblb.correct().string

'hello this is jack'

# Stopwords Removal

In [29]:
text = """
Yesterday, I was working on a Machine Learning project in PHITRON, and I was trying to understand how the model is performing on the dataset. The dataset is quite large, and it contains a lot of reviews that are written by users from different countries.

I noticed that the model is not performing well for some of the samples, especially those that are very short or have too many stopwords in them. Because of this, I decided to clean the text data and remove unnecessary words that do not contribute much to the meaning of the sentence.

While I was doing this, I also checked how the preprocessing steps like tokenization, lowercasing, and punctuation removal are affecting the dataset. It was interesting to see that after removing stopwords, the text becomes more meaningful and easier for the model to understand.

In addition to that, I was also reading some documentation from https://scikit-learn.org/stable/ and watching tutorials on https://www.youtube.com while comparing different NLP techniques. The goal is to improve the accuracy of the model and make it more robust for real-world applications.

Overall, I think that removing stopwords is an important step in the NLP pipeline because it helps reduce noise and improve performance of machine learning models.
"""

In [30]:
import nltk

In [31]:
from nltk.corpus import stopwords

In [32]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [33]:
stop_words = set(stopwords.words('english'))

In [34]:
stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 "we've",
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [35]:
def remove_stopwords(text):
  words = text.split()
  cleaned = []

  for word in words:
    word = word.lower().strip(string.punctuation)

    if word and word not in stop_words:
      cleaned.append(word)
  return " ".join(cleaned)

In [36]:
remove_stopwords(text)

'yesterday working machine learning project phitron trying understand model performing dataset dataset quite large contains lot reviews written users different countries noticed model performing well samples especially short many stopwords decided clean text data remove unnecessary words contribute much meaning sentence also checked preprocessing steps like tokenization lowercasing punctuation removal affecting dataset interesting see removing stopwords text becomes meaningful easier model understand addition also reading documentation https://scikit-learn.org/stable watching tutorials https://www.youtube.com comparing different nlp techniques goal improve accuracy model make robust real-world applications overall think removing stopwords important step nlp pipeline helps reduce noise improve performance machine learning models'

In [37]:
df['review'] = df['review'].apply(remove_stopwords)

In [38]:
df['review']

0        one reviewers mentioned watching 1 oz episode ...
1        wonderful little production br br filming tech...
2        thought wonderful way spend time hot summer we...
3        basically there's family little boy jake think...
4        petter mattei's love time money visually stunn...
                               ...
11033    zentropa much common third man another noir-li...
11034    warning:i advise anyone seen film yet read com...
11035    ego seems reason movie made movie wrong many w...
11036    meant comedy mainly bad taste nothing remotely...
11037    typically kids films annoying quality makes wa...
Name: review, Length: 11038, dtype: object

# Emoji removal

In [39]:
text_with_emoji = '''Yesterday I completed my Machine Learning project on sentiment analysis 😊🔥.
The model performed really well on the IMDB dataset 👍🎯.
I learned a lot about preprocessing steps like tokenization, stopwords removal, and stemming 📚💡.
However, debugging errors was quite frustrating 😓💻.
Overall, the experience was amazing and I feel more confident now 🚀😄.'''

In [40]:
import re

def remove_emoji(text):
  emoji_pattern = re.compile(
      "["
        "\U0001F600-\U0001F64F"  # emoticons
        "\U0001F300-\U0001F5FF"  # symbols & pictographs
        "\U0001F680-\U0001F6FF"  # transport & map symbols
        "\U0001F1E0-\U0001F1FF"  # flags
        "\U00002700-\U000027BF"  # dingbats
        "\U000024C2-\U0001F251"
        "]+",
        flags=re.UNICODE
  )
  return emoji_pattern.sub(r'', text)

In [41]:
clean_text = remove_emoji(text_with_emoji)
print(clean_text)

Yesterday I completed my Machine Learning project on sentiment analysis .
The model performed really well on the IMDB dataset .
I learned a lot about preprocessing steps like tokenization, stopwords removal, and stemming .
However, debugging errors was quite frustrating .
Overall, the experience was amazing and I feel more confident now .

# Tokenization

## NLTK

In [42]:
from nltk.tokenize import word_tokenize, sent_tokenize
import nltk

In [43]:
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [44]:
sent1 = 'I am going to visit Dhaka!'
word_tokenize(sent1)

['I', 'am', 'going', 'to', 'visit', 'Dhaka', '!']

In [45]:
text = """Lorem Ipsum is simply dummy text of the printing and typesetting industry?
Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,
when an unknown printer took a galley of type and scrambled it to make a type specimen book."""

sent_tokenize(text)

['Lorem Ipsum is simply dummy text of the printing and typesetting industry?',
 "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,\nwhen an unknown printer took a galley of type and scrambled it to make a type specimen book."]

In [51]:
sent5 = 'I have a Ph.D in A.I'
sent6 = "We're here to help! mail us at abc@gmail.com"
sent7 = 'A 3km ride cost $15.50'

In [52]:
word_tokenize(sent5)

['I', 'have', 'a', 'Ph.D', 'in', 'A.I']

In [53]:
word_tokenize(sent6)

['We',
 "'re",
 'here',
 'to',
 'help',
 '!',
 'mail',
 'us',
 'at',
 'abc',
 '@',
 'gmail.com']

In [54]:
word_tokenize(sent7)

['A', '3km', 'ride', 'cost', '$', '15.50']

## Spacy

In [55]:
import spacy
nlp = spacy.load('en_core_web_sm')

In [56]:
doc1 = nlp(sent5)
doc2 = nlp(sent6)
doc3 = nlp(sent7)
doc4 = nlp(sent1)

In [58]:
for token in doc1:
    print(token)

I
have
a
Ph
.
D
in
A.I

In [57]:
for token in doc2:
    print(token)

We
're
here
to
help
!
mail
us
at
abc@gmail.com

In [59]:
for token in doc3:
    print(token)

A
3
km
ride
cost
$
15.50

In [60]:
for token in doc4:
    print(token)

I
am
going
to
visit
Dhaka
!

## Stemming

In [61]:
from nltk.stem.porter import PorterStemmer

In [62]:
ps = PorterStemmer()

def stem_words(text):
  return " ".join([ps.stem(word) for word in text.split()])

In [63]:
sample = "walk walks walking walked"
stem_words(sample)

'walk walk walk walk'

In [64]:
text = 'probably my alltime favorite movie a story of selflessness sacrifice and dedication to a noble cause but its not preachy or boring it just never gets old despite my having seen it some 15 or more times in the last 25 years paul lukas performance brings tears to my eyes and bette davis in one of her very few truly sympathetic roles is a delight the kids are as grandma says more like dressedup midgets than children but that only makes them more fun to watch and the mothers slow awakening to whats happening in the world and under her own roof is believable and startling if i had a dozen thumbs theyd all be up for this movie'
print(text)

probably my alltime favorite movie a story of selflessness sacrifice and dedication to a noble cause but its not preachy or boring it just never gets old despite my having seen it some 15 or more times in the last 25 years paul lukas performance brings tears to my eyes and bette davis in one of her very few truly sympathetic roles is a delight the kids are as grandma says more like dressedup midgets than children but that only makes them more fun to watch and the mothers slow awakening to whats happening in the world and under her own roof is believable and startling if i had a dozen thumbs theyd all be up for this movie

In [66]:
stem_words(text)

'probabl my alltim favorit movi a stori of selfless sacrific and dedic to a nobl caus but it not preachi or bore it just never get old despit my have seen it some 15 or more time in the last 25 year paul luka perform bring tear to my eye and bett davi in one of her veri few truli sympathet role is a delight the kid are as grandma say more like dressedup midget than children but that onli make them more fun to watch and the mother slow awaken to what happen in the world and under her own roof is believ and startl if i had a dozen thumb theyd all be up for thi movi'

# Lemmatization

In [67]:
import nltk
from nltk.stem import WordNetLemmatizer

In [68]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [78]:
wordnet_lemmatizer = WordNetLemmatizer()

In [70]:
sentence = "He was running and eating at same time. He has bad habit of swimming after playing long hours in the Sun."

In [71]:
punctuations="?:!.,;"

In [73]:
sentence_words = nltk.word_tokenize(sentence)

In [74]:
for word in sentence_words:
    if word in punctuations:
        sentence_words.remove(word)

In [75]:
sentence_words

['He',
 'was',
 'running',
 'and',
 'eating',
 'at',
 'same',
 'time',
 'He',
 'has',
 'bad',
 'habit',
 'of',
 'swimming',
 'after',
 'playing',
 'long',
 'hours',
 'in',
 'the',
 'Sun']

In [76]:
print("{0:20}{1:20}".format("Word","Lemma"))  ## formating

Word                Lemma

In [79]:
for word in sentence_words:
    print ("{0:20}{1:20}".format(word,wordnet_lemmatizer.lemmatize(word,pos='v')))

He                  He
was                 be
running             run
and                 and
eating              eat
at                  at
same                same
time                time
He                  He
has                 have
bad                 bad
habit               habit
of                  of
swimming            swim
after               after
playing             play
long                long
hours               hours
in                  in
the                 the
Sun                 Sun